[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/v/*"
  to = "/index.html"
  status = 200

[functions."purge-scheduled"]
  schedule = "@daily"

[functions."upload-chunked-complete"]
  timeout = 26
